### ISSUE TITLE
Habits should be sortable

### ISSUE THREAD

**Issue by tylermumford** [goodtohear/habits#10]
I suggest using one of three methods for sorting habits:
1. Allowing the user to reorder habits
2. Always sorting by name
3. Sorting by starting reminder time first, then name

Thoughts?

**Comment by michaelforrest** [comment]
I think I prefer option 3. Thanks for raising this here.

**Comment by kristopherjohnson** [comment]
I'd vote for allowing user to sort manually. I like to list them in chronological order, but I could also see a desire to group them in other ways (by work-vs.-play, or by location, for example).

**Comment by michaelforrest** [comment]
Yep I've been thinking about this too and I agree. I'll do it with a press and hold to start dragging rather than trying to add an Edit button.

**Comment by michaelforrest** [comment]
Done in 1.1
