### ISSUE TITLE
Export Data Feature

### ISSUE THREAD

**Issue by sanjeevphd** [goodtohear/habits#24]
It would be great if the app can export data in a simple format (csv via email for instance), in order to analyze and visualize the habit data. This might encourage developers to write simple APIs for performing analytics and visualizing the data. I also imagine APIs that take the raw data dumped by the app and parse it into a mainstream format (csv, json, etc.). API users can post the visualizations on their blogs or Facebook, etc., which could potentially increasing the user base for the app. Thanks.

**Comment by katylava** [comment]
Agreed. Ideally with time stamps for when items were checked off... But that's another feature request. Just being able to export the data would be handy.

**Comment by michaelforrest** [comment]
+1 from Tomas.

**Comment by funky-monkey** [comment]
The option export is there, on my 5S it crashes every time i select it. It shows a spinner and then force closes. Can this be fixed?

**Comment by michaelforrest** [comment]
Hi @funky-monkey, I can see a few users experiencing the same issue. Do you have an email account configured on your phone? If not, can you check whether the app still crashes if you set one up?
Thanks

**Comment by funky-monkey** [comment]
I use a different app than the native one. 
In my opinion the export function should not be in any way dependent of mail. Maybe export to UIPasteboard? That way your users, can take that export-information to any source they want/can. (but if you are willing to implement the Dropbox API i'm not going to stop you ;-) )

**Comment by michaelforrest** [comment]
This is resolved in 2.0.4 (pending approval)

**Comment by funky-monkey** [comment]
Really great to have this feature! I just updated to the latest version of the app.
I do however just lost all of my data because of this update. That is not so nice. Maybe something to look into (CoreData migration issue?).

Hope this helps!
Sid

**Comment by michaelforrest** [comment]
ARGH is the only response to that. I didn't even touch core data in this update! I have no idea how to debug this thing where people's data seems to vanish on the whims of the system. Did you log in with a different Apple ID recently? Does your data reappear if you log in with the previous one?

**Comment by funky-monkey** [comment]
Yes, the device is my test device which I use with different Apple ID's. 
But I recently switched to iCloud Drive so that could also be an issue... But this is probably a _rare race condition_ since everybody already switched to iCloud Drive (except me that is ;-) )

**Comment by michaelforrest** [comment]
It's rare but it does seem to have happened to a few other people. iCloud Drive could be the explanation, come to think of it. Real pain to figure out without being able to plug Xcode into someone's actual phone though.

**Comment by funky-monkey** [comment]
Do you keep logs within the bundle of the app? I could pull them out and send them to you.
Also you can debug iCloud Drive; I think Apple has some docs and technotes on it.

**Comment by funky-monkey** [comment]
https://developer.apple.com/library/ios/documentation/DataManagement/Conceptual/UsingCoreDataWithiCloudPG/UsingiCloudDebuggingTools/UsingiCloudDebuggingTools.html

Hope this helps you - If i can test for you, just shoot!

**Comment by michaelforrest** [comment]
Yes, I can debug iCloud if I can plug a problematic phone into Xcode but that's not the problem - luckily there isn't much code to go wrong so I'm going to see if there's something simple I can try to fix this...

**Comment by michaelforrest** [comment]
Here's what should work: log out of iCloud and see if your data re-appears. If so, export it before logging back into iCloud then importing it back into the app. If your data doesn't appear on logging out then try a different iCloud account until you find it.

**Comment by michaelforrest** [comment]
Hi @funky-monkey - it looks like when Xcode was mucking about with provisioning profiles it reset the iCloud container to 'Use default container'. I want to send you a testing build to verify that I've fixed the problem - would you mind sharing your email address? Email info@goodtohear.co.uk

**Comment by funky-monkey** [comment]
I though I send you a mail... Did it arrive? Anyways - sidney.dekoning@gmail.com

Cheers!

**Comment by michaelforrest** [comment]
Hi @funky-monkey - did your data reappear with 2.0.5?
