### ISSUE TITLE
Select days of month

### ISSUE THREAD

**Issue by ap64** [goodtohear/habits#25]
Please don't change anything else but please add ability to select a single day per month for specific items (pay mortgage, make car payment, etc). Also allow ability to select one day per year things like birthdays and anniversaries.

**Comment by michaelforrest** [comment]
Hi, thanks for this suggestion. 

Good Habits is designed as a habit-forming tool, primarily focused on daily habits. I didn't mind stretching it to weekly habits but I feel that monthly or annual intervals are not really in the habit-forming realm and would be better served with a more conventional calendar app. As such, I need to close this issue.
