### ISSUE TITLE
More colors, choose colors

### ISSUE THREAD

**Issue by katylava** [goodtohear/habits#26]
I'd like to be able to choose a color from a traditional color picker for each task. Obviously not critical for use of the app, just a would-be-nice feature.

**Comment by Annafranki** [comment]
For me this this one is very important. In other things, this app is very good.

**Comment by michaelforrest** [comment]
Closed in v2.0, in the App Store now.

**Comment by michaelforrest** [comment]
(Except for the more colours bit. I might add 'shades' at some point but probably not)
