### ISSUE TITLE
Documentation: how to mark a habit 'completed'

### ISSUE THREAD

**Issue by cllns** [goodtohear/habits#31]
It seems obvious now, but it took me a couple minutes to figure out how to 'complete' a habit for the day. (Other apps, such as Lift do it by swiping the task)

The colored box didn't immediately stand out to me as a check box. Perhaps add a thin border to the boxes?

Maybe a screenshot in 'the guide' would help as well.

**Comment by michaelforrest** [comment]
Can't say I agree with this one! All the app store screenshots show check marks. 
The new video guide probably represents this though.
