### ISSUE TITLE
Support periodic habits

### ISSUE THREAD

**Issue by nomicode** [goodtohear/habits#34]
Habit List has a great feature where you can specify that the habit should only be completed once ever 1-2 days, 3-5 days, 5-7 days, and so on. You can even specify that it should only be done on specific days. This is great for some things that should be done regularly, but not necessarily daily.

It would be neat it Good Habits supported this too.

**Comment by michaelforrest** [comment]
I have always felt this complicates the UI too much and that habit-forming is better done on a daily or day-of-the-week basis. I have no plans to implement this feature.
