### ISSUE TITLE
Cannot set reminder

### ISSUE THREAD

**Issue by emom21** [goodtohear/habits#36]
Reminder box stays as No Reminder and does not have Set Reminder ability

**Comment by NLarson2639** [comment]
Same issue:  created one habit that worked, others don't set reminders.  ???

**Comment by smadison04** [comment]
I have this problem, also. Very frustrating.

**Comment by michaelforrest** [comment]
Duplicate of #32, now closed.

**Comment by NLarson2639** [comment]
Why did you close my query, #36?  It remains unanswered!

Sent from Acompli_____________________________From: Michael Forrest notifications@github.com
Sent: Tuesday, October 14, 2014 8:20 AM
Subject: Re: [habits] Cannot set reminder (#36)
To: goodtohear/habits habits@noreply.github.com
Cc: NLarson2639 jandnlarson2639@gmail.com

Closed #36.

**Comment by michaelforrest** [comment]
As it says above, this is a duplicate of bug #32 where you can find more explanation.

**Comment by NLarson2639** [comment]
I have an iPhone 5c with iOS 8.1.  If I click on the task I want to edit, it only changes the checkbox.

How can I amend the reminder time and/or the time for the task?

**Comment by michaelforrest** [comment]
Are you running the latest update from the App Store? A big update came out on Saturday. You should be able to tap the task name to edit the reminder.

**Comment by NLarson2639** [comment]
I got that part.  Thanks!

Is there a way to change something on a task itself?

**Comment by michaelforrest** [comment]
I'm not sure I understand the question "Is there a way to change something on a task itself?"... can you clarify please?

**Comment by NLarson2639** [comment]
I have a task scheduled for a certain time each day.  I would like to change the time for it.
