### ISSUE TITLE
Data Export Not Working

### ISSUE THREAD

**Issue by lookaroundforinspiration** [goodtohear/habits#37]
I use Good Habits app and would like to export my data. However, every time I go through the steps on the app to export it (I know I'm doing this part right), there is no data file attached to the email. I have tried clicking on the file before sending it, from my smartphone, but that doesn't work either. Is there anyone else who has been able to successfully export their GoodHabits data? Is anyone else having this problem? What can I do?

**Comment by michaelforrest** [comment]
Hi, are you still having this problem on the new build?

**Comment by michaelforrest** [comment]
Ok I'm closing this as I'm sure it's okay in 2.0.

**Comment by lookaroundforinspiration** [comment]
Hi, no it still is not working. The JSON file does not appear in the delivered email. It doesn't attach and there isn't an alternative clickable link that the information could be in. 

Jackie Fullerton

**Comment by michaelforrest** [comment]
This _might_ be something to do with your email client. For example, I think gmail squashes the data link (which is only useful on the device anyway). Furthermore, your email client might consider the attachment a security vulnerability and remove it. 

How are you opening the email?
