### ISSUE TITLE
Check marks are not saving

### ISSUE THREAD

**Issue by pernotto99** [goodtohear/habits#38]
Every time I close the app, none of the check marks are saved the next time I open it. This has been a recent change. I do not want to lose all of my data by reinstalling.

**Comment by kevinapp** [comment]
Same problem here. Started happening right after upgrading to iOS 8.

**Comment by danceallnight** [comment]
Same problem, hasn't save anything past September 18th for me.

**Comment by dwpike** [comment]
Happened after ios8 upgrade for me as well

**Comment by khaylova** [comment]
The same problem after ios8 upgrade for me as well too.

**Comment by brunogodbout** [comment]
Same for me too.

**Comment by inkymama** [comment]
Me too--uninstalling and reinstalling and trying to restore data does nothing.

**Comment by justinluey** [comment]
Same thing after updating to iOS 8.

**Comment by alex---andra** [comment]
same problem after updating to iOS 8. Very annoying

**Comment by michaelforrest** [comment]
Closed in v2.0, in the App Store now.
