### ISSUE TITLE
Please release iOS 8 update so I can continue to use this great app

### ISSUE THREAD

**Issue by needhelpnow** [goodtohear/habits#43]
This is happening to me too.  Since upgrading to iOS 8 Good Habits doesn't save your checks, even if you don't close app, the next day all your checks are gone.  Deleted, reinstalled but that didn't fix the problem.  Please update app for iOS 8 so I can continue with my good habits, it's been so helpful in my life, I really appreciate it, thank you!

**Comment by michaelforrest** [comment]
Closed in v2.0 - available now in the App Store.
