### ISSUE TITLE
Scrolling 

### ISSUE THREAD

**Issue by bvlavern** [goodtohear/habits#48]
The good habit app doesn't scroll down if I have more than seven habits. Could you please update the app with scrolling capabilities?

**Comment by michaelforrest** [comment]
I need some more detail on this (as I am able to scroll through a very long list myself!) 
What device are you using? Would you mind exporting your data and sending to info@goodtohear.co.uk?

**Comment by AlegriaL** [comment]
I have 17 active habits and 3 paused ones, and I can only scroll down until the first paused one. So I can't actually unpause either of my last 2 paused habits.

**Comment by AlegriaL** [comment]
I'm using iOS 7 by the way, and the latest version of Good Habits.

**Comment by michaelforrest** [comment]
And which device? I am guessing an iPhone 4 or an iPad? I have reproduced some scrolling problems when trying a long list on a shorter screen - I can elastically pull down to the bottom of a long list but then it springs back to maybe the second or third last item making it impossible to interact. Does that sound like your problem?

**Comment by bvlavern** [comment]
Exactly!!! ;). 

Is there something we can do? 
You see I am using this tool to help my daughter stay on tract. :). 

Can you please help a caring momma. ;)

V/r,
Bertillia Lavern 
Great things come to those whom believe!!!
www.marykay.com/bvlavern

**Comment by AlegriaL** [comment]
That's exactly my problem too, and yes I'm using an iPhone 4.

—

**Comment by michaelforrest** [comment]
Fixed in 8.0.2

**Comment by bvlavern** [comment]
Thank you so much!!!

V/r,
Bertillia Lavern 
Great things come to those whom believe!!!
www.marykay.com/bvlavern
