### ISSUE TITLE
App icon badge out of sync

### ISSUE THREAD

**Issue by michaelforrest** [goodtohear/habits#50]
A user reported that the icon badge had a 6 when there were only 4 outstanding task for that day.

**Comment by ulyssesbbg** [comment]
Michael, is there anything I can do to help you resolve this?  Already tried: deleting and reinstalling the app, deleting all of your app's iCloud data, resetting the time zone on my phone (to Pacific), and rebooting the phone.

Even with a fresh start and not importing any of the old data, and the latest version of the app (2.0.2) and iOS (8.1.2), I still have the same problem:
- IF it's late in the day,
- ... the Habits icon badge resets to the total number of habits (as if it's a new day),
- ... no matter how many outstanding tasks there are left for the current day.

I see in my JSON data that you're recording all dates in GMT: "date":"2014-11-18 00:00:00 +0000" - could this have something to do with it?  Shouldn't the date be recorded in the customer's time zone?  Or do you calculate the offset elsewhere?

JSON excerpt:

``` json
"order":5,"daysRequired":["Mon","Tue","Wed","Thu","Fri","Sat"],"title":"Openstack training","identifier":"D0239587-1E73-4FF1-80A7-4E830C1CB65D","createdAt":"2014-11-25 16:18:11 +0000","isActive":1},{"chains":[{"days":[{"date":"2014-10-23 00:00:00 +0000","runningTotal":0},{"date":"2014-10-24 00:00:00 +0000","runningTotal":1},{"date":"2014-10-27 00:00:00 +0000","runningTotal":2},{"date":"2014-10-28 00:00:00 +0000","runningTotal":3},{"date":"2014-10-29 00:00:00 +0000","runningTotal":4},{"date":"2014-10-30 00:00:00 +0000","runningTotal":5},{"date":"2014-10-31 00:00:00 +0000","runningTotal":6},{"date":"2014-11-03 00:00:00 +0000","runningTotal":7},{"date":"2014-11-04 00:00:00 +0000","runningTotal":8},{"date":"2014-11-05 00:00:00 +0000","runningTotal":9},{"date":"2014-11-06 00:00:00 +0000","runningTotal":10},{"date":"2014-11-07 00:00:00 +0000","runningTotal":11},{"date":"2014-11-10 00:00:00 +0000","runningTotal":12},{"date":"2014-11-11 00:00:00 +0000","runningTotal":13},{"date":"2014-11-12 00:00:00 +0000","runningTotal":14}]},{"days":[{"date":"2014-11-14 00:00:00 +0000","runningTotal":0},{"date":"2014-11-15 00:00:00 +0000","runningTotal":1},{"date":"2014-11-16 00:00:00 +0000","runningTotal":2},{"date":"2014-11-17 00:00:00 +0000","runningTotal":3},{"date":"2014-11-18 00:00:00 +0000","runningTotal":4}]},{"days":[{"date":"2014-11-21 00:00:00 +0000","runningTotal":0},{"date":"2014-11-24 00:00:00 +0000","runningTotal":1},{"date":"2014-11-25 00:00:00 +0000","runningTotal":2}]},{"days":[{"date":"2014-11-27 00:00:00 +0000","runningTotal":0}]},{"days":[{"date":"2014-12-01 00:00:00 +0000","runningTotal":0},{"date":"2014-12-02 00:00:00 +0000","runningTotal":1},{"date":"2014-12-03 00:00:00 +0000","runningTotal":2},{"date":"2014-12-04 00:00:00 +0000","runningTotal":3},{"date":"2014-12-05 00:00:00 +0000","runningTotal":4},{"date":"2014-12-08 00:00:00 +0000","runningTotal":5}]},{"days":[{"date":"2014-12-10 00:00:00 +0000","runningTotal":0}]}],"color":"#488FB4"
```

Screenshots (cropped), you'll see 7 tasks checked with 2 remaining.  **_I expect to see a 2 on the icon badge, but instead I see a 9 on the badge.**_

![img_5902](https://cloud.githubusercontent.com/assets/3385995/5407433/f1617c1c-817a-11e4-97a9-6b4d43e9d42e.jpg)    ![img_5901](https://cloud.githubusercontent.com/assets/3385995/5407432/f144dc38-817a-11e4-8e70-2bb0298ab3ba.jpg)

Thanks and looking forward to your reply.

**Comment by michaelforrest** [comment]
Hi, thanks for this detailed bug report! I submitted a build last night with a fix for this bug. It should be through in a few days.

**Comment by ulyssesbbg** [comment]
That's fantastic, thanks Michael!  Looking forward to the new build.
