### ISSUE TITLE
Can't access paused habits on iphone 4S

### ISSUE THREAD

**Issue by croxanas** [goodtohear/habits#51]
I can't access pause habits on iphone 4S ios 7.1.2
I scroll up to see the paused habits but when I let go to select the habit I want to unpause it springs back up to the top. Very frustrating.

**Comment by croxanas** [comment]
*scroll down I meant...(was thinking drag up to see the bottom of the list)

**Comment by michaelforrest** [comment]
Fixed in next build - just waiting for Apple to review.

**Comment by croxanas** [comment]
Awesome! Thank you! Love the app btw.
