### ISSUE TITLE
Month View Showing Wrong Days/Dates

### ISSUE THREAD

**Issue by aslamn** [goodtohear/habits#53]
Opened the app today and went to Month View to mark a previous day that I had done my task and I noticed that October 16, 2014 is showing as being on a Friday but it was actually on a Thursday. And also that today, Tuesday, is showing as October 20 when it is the 21st.

**Comment by matthiasotto** [comment]
Confirmed. I am seeing this too.

**Comment by michaelforrest** [comment]
Fixed in next build - I'm just waiting for Apple to review.
