### ISSUE TITLE
Start screen - See previous longest chain

### ISSUE THREAD

**Issue by Schmedu** [goodtohear/habits#54]
Seeing your previous longest chain and your current chain was a big motivation for me & I think for a lot of other users too!

Now, when I want to see the longest previous chain, I need to go to the stats, which, by the way, I purchased because you guys made a great app, and look there.

Although, I've got to admit that the new design looks quite good & you made a good job on the new version. It would be really helpful, if you could show the longest previous chain again!

**Comment by michaelforrest** [comment]
Hi, thanks for your email.
You can see the previous longest chain at any time (without an in app
purchase) by tapping the current chain length number. I could probably do a
better job of documenting this but I was aware that people would be unhappy
if I made this disappear forever.
I have some things I will be trying in future versions though that will
help you be more aware of how you're doing.
All the best
Michael

**Comment by Schmedu** [comment]
Hey Michael,

thanks for your fast reply! I have tested it and you're right, thanks!

If you like to, I would make the suggestion, that by tapping on the current chain length number you could receive the old view with the current and longest chain length number.

This could be a nice workaround! You could implement it easily, because you have the design and code of the old version & people like me, who loved the big motivation behind it, would also be happy =)

Please let me know, if this would be a solution for you.

Thank you!

**Comment by michaelforrest** [comment]
I'm hoping you're used to this now...
