### ISSUE TITLE
Notes Not Working

### ISSUE THREAD

**Issue by skapocalypse** [goodtohear/habits#59]
I just purchased the Stats functionality on iOS 8.  I do not get the option to add a note, as shown in the guide video.  What gives?

**Comment by michaelforrest** [comment]
Hi, you may have turned this off at an earlier stage. Can you try going into your iPhone's Settings app, find Habits and switch on "Enable in-app purchases"? 
I'll make a change that should prevent this situation for future updates.

**Comment by skapocalypse** [comment]
That was it!  Thanks!  I am good.
