### ISSUE TITLE
Badges and days

### ISSUE THREAD

**Issue by Hilapy** [goodtohear/habits#60]
App seems to be confused about what day it is. On the list for today, it has the correct day and date. But where it lists habits not scheduled for today (Saturday) it says Not on Sundays. They are in fact habits that I've scheduled for Sundays. So it's correct that they're not due today, but it's calling today Sunday in that spot. I think it may be affecting or somehow connected to the badge, which is also incorrect. I've done all but one of my habits for today but the badge says I have 7 left. I'm using an iPhone 4 w iOS 7.1.2. It's been happening ab

**Comment by Hilapy** [comment]
About a week I think.

**Comment by michaelforrest** [comment]
Hi, this should be fixed in the latest update (which came out on Sunday). Can you check whether you're still having this problem with the latest version? Thanks.

**Comment by Hilapy** [comment]
Thanks. Badge is working now, but it's still confused about the day. But do I have to do anything about the update? I didn't tell it to update - maybe that happens on its own. Sorry not very used to smartphones yet.

**Comment by Hilapy** [comment]
Hm, now it's reminding me to do a habit that I don't have scheduled for today.

**Comment by michaelforrest** [comment]
Hi @Hilapy, can you be any more specific about this? Would you mind sending me an export of your data if you're still experiencing this problem? (Info screen->Export your data.. and send to info@goodtohear.co.uk )
