### ISSUE TITLE
Swipe left for retrospective update - can't find it

### ISSUE THREAD

**Issue by baob** [goodtohear/habits#61]
Hi,

The animation in the app shows that if you swipe left on a habit, you get the opportunity to make an update for the previous day. However I can't find this while using the app (either iPad mini/IOS8 or iPhone 4S/ISO7).

I have a suspicion this may be related to switch from Ruby to a rebuilt app in Objective C, but in any case  it would be useful to have this feature.

Thanks, Andy

**Comment by michaelforrest** [comment]
It will only let you swipe left if you missed the previous day - could that be the problem? If that's not it, perhaps you could record a 'video bug report' via the info section and talk me through the problem? Thanks

**Comment by baob** [comment]
Sorry for not responding. I've since stopped using the app. Please close the ticket if you're still keeping it open for my benefit.
