### ISSUE TITLE
App crashed 

### ISSUE THREAD

**Issue by davinfung** [goodtohear/habits#72]
My Good Habits app that I've been using since Sept 2015 crashed yesterday. It will launch and then shut down. I finally had to delete and reinstall the app. Once installed, I cannot find a way to restore the data. There's a file in iCloud. I am on an iPhone 5 iOS v. 9.3.2. I also paid for the upgrade or stats unlock which I don't think does much. 

What do I do?

**Comment by michaelforrest** [comment]
Sorry for not following up on this at the time. i'm back now. I hope you got it resolved.
