### ISSUE TITLE
Immediately Minimizes after adding tracking

### ISSUE THREAD

**Issue by clittle1973** [goodtohear/habits#74]
The app works well until you purchase the tracking, then becomes unusable. After adding a comment to one of the habits in the main window, after either closing or changing focus to a different app Good Habits will not stay in focus and when opened or refocusing the app window it immediately minimizes.  To fix you have to uninstall, reinstall, and not restore your purchase or add any tracking comments to habits.
Apple iPhone 6 Plus
IOS 10
60GB
25GB free

**Comment by jordipuente** [comment]
Same problem
