### ISSUE TITLE
"Dec 2020" title appears instead of "Jan 2020"

### ISSUE THREAD

**Issue by seltzered** [goodtohear/habits#76]
Hi, started trying this app and noticed that "Dec 2020" appears today (december 31st, 2019) instead of "Jan 2020". The issue resolves itself when going back a month then forward.

![IMG_4307-2](https://user-images.githubusercontent.com/297435/71638138-96d51c80-2c0c-11ea-8b8f-0fd03ece698e.png)

**Comment by michaelforrest** [comment]
Didn't expect to still see a bug like this after several years - I must have an incorrect time zone assumption in there somewhere. I will see if I can reproduce it!

**Comment by michaelforrest** [comment]
Fixed (I had YYYY instead of yyyy in a date format. Classic error...)
