### ISSUE TITLE
Good habits in widgets screen white out

### ISSUE THREAD

**Issue by joshua50n** [goodtohear/habits#77]
Unable to view good habits in widgets screen.. it’s all whited out. You can still check the boxes.. but can’t see what you’re checking

**Comment by michaelforrest** [comment]
Hi, thanks for this report! I'd noticed it in the corner of my eye one evening and now I realise that it's a Dark Mode problem. I'm fixing the bug and pushing a build this morning.

**Comment by joshua50n** [comment]
You are amazing 
Thank you!
