### ISSUE TITLE
Total Days Checked Not Totaling Properly

### ISSUE THREAD

**Issue by samsonMC** [goodtohear/habits#80]
The total days checked is not calculating correctly

**Comment by michaelforrest** [comment]
Hi @samsonMC , can you be any more specific? Totals seem okay for me so it would be easier for me to debug this if I had a screenshot or something from you.
Thanks
Michael

**Comment by samsonMC** [comment]
![F2175C8E-FBF1-4D95-BC60-A1D3352E37B9](https://user-images.githubusercontent.com/75872306/102104778-d11ed600-3deb-11eb-8125-c30461c2f32b.png)

**Comment by samsonMC** [comment]
I've got a total of 41 chains and the longest chain is 24 days but it only says the total number of days is 29

**Comment by michaelforrest** [comment]
Interesting.... Ok I'll investigate this asap.

**Comment by samsonMC** [comment]
I'm having problems with the total calculation again. The total says 56 but if you add to the amount each month from my trends it's actually only 55
![D634F775-311C-4EC8-881E-D1954B9D8ED1](https://user-images.githubusercontent.com/75872306/227815778-3b97d057-9f04-41cd-a091-2548c2616bc5.png)
![50E88F52-56B0-4C57-8E32-AB019F482368](https://user-images.githubusercontent.com/75872306/227815780-3fb92371-c21c-4594-bf28-ff6f5301cc38.png)
![82288E42-6E8D-47EF-A021-16B10669C38A](https://user-images.githubusercontent.com/75872306/227815785-6815294b-8843-45cd-b116-67408ce8b880.png)
![7939D72B-F19A-4661-BA3F-1FA7480FE236](https://user-images.githubusercontent.com/75872306/227815786-b7b1285f-2150-41d4-b5cd-4e8b589132ca.png)
