### ISSUE TITLE
Landscape mode is unneeded

### ISSUE THREAD

**Issue by tylermumford** [goodtohear/habits#9]
Most iPhone apps don't permit rotation into landscape mode unless there's a lot of typing to be done. I think this app would benefit from being portrait-only.

Also, landscape mode doesn't scale well in the app's current state, so it should probably at least be removed until it's ready.

**Comment by michaelforrest** [comment]
Yes I think this is an iOS 6 bug - it doesn't rotate at all in iOS 5. Will fix for 1.0.2
